# Generated by Django 6.0.2 on 2026-06-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('google_forms', 'Google Forms'), ('other', 'Other Platform')], max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('revoked', 'Revoked'), ('disconnected', 'Disconnected'), ('pending', 'Pending Verification')], default='active', max_length=20)),
                ('account_metadata', models.JSONField(default=dict)),
                ('permissions', models.JSONField(default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connected Account',
                'verbose_name_plural': 'Connected Accounts',
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(max_length=50)),
                ('config_type', models.CharField(choices=[('oauth', 'OAuth Connection'), ('api_key', 'API Key'), ('webhook', 'Webhook'), ('custom', 'Custom Config')], default='oauth', max_length=20)),
                ('config_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Config',
                'verbose_name_plural': 'Integration Configs',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(max_length=100)),
                ('budget', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('source_legacy', models.CharField(choices=[('website', 'Website Form'), ('landing_page', 'Landing Page'), ('google_forms', 'Google Forms'), ('facebook_ads', 'Facebook Lead Ads'), ('instagram_ads', 'Instagram Ads'), ('instagram_dms', 'Instagram DM'), ('whatsapp', 'WhatsApp Inquiry'), ('manual', 'Manual Entry'), ('google_maps', 'Google Maps'), ('other', 'Other')], default='manual', help_text="Legacy source field. Use 'source' ForeignKey instead.", max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID from external platform (Facebook, Instagram, etc.)', max_length=500, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw data received from external platform')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('converted', 'Converted'), ('not_interested', 'Not Interested'), ('closed', 'Closed'), ('qualified', 'Qualified'), ('meeting', 'Meeting Scheduled'), ('proposal', 'Proposal Sent'), ('lost', 'Lost'), ('archived', 'Archived')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Lead qualification score (0-100)')),
                ('ai_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('connected_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.connectedaccount')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Lead Created'), ('updated', 'Lead Updated'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned to User'), ('contacted', 'Contacted'), ('note_added', 'Note Added'), ('synced', 'Synced from Integration'), ('merged', 'Merged with Another Lead'), ('archived', 'Archived')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('instagram_dms', 'Instagram Direct Messages'), ('google_forms', 'Google Forms'), ('google_maps', 'Google Maps Business'), ('website_form', 'Website Form'), ('landing_page', 'Landing Page'), ('whatsapp', 'WhatsApp Inquiry'), ('email', 'Email Inquiry'), ('manual', 'Manual Entry'), ('api', 'API Integration'), ('other', 'Other Source')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'unique_together': {('name', 'source_type')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('call', 'Call Lead'), ('email', 'Send Email'), ('meeting', 'Schedule Meeting'), ('followup', 'Follow Up'), ('proposal', 'Send Proposal'), ('other', 'Other Task')], default='call', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('user', 'User'), ('client', 'Client')], default='user', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['user', 'account_type'], name='crm_connect_user_id_3db3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedaccount',
            index=models.Index(fields=['status', 'sync_enabled'], name='crm_connect_status_c33c01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connectedaccount',
            unique_together={('user', 'account_type', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('integration_type', 'config_type')},
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='crm_leadact_lead_id_639066_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['activity_type', '-created_at'], name='crm_leadact_activit_c678b2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone', 'email'], name='crm_lead_phone_693602_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'priority'], name='crm_lead_status_317d75_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='crm_lead_created_deedb3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lead', 'status'], name='crm_task_lead_id_07e55f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_task_assigne_1d8686_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='crm_task_due_dat_2a3684_idx'),
        ),
    ]
