# Generated by Django 6.0.5 on 2026-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Form'), ('google_forms', 'Google Forms'), ('instagram_ads', 'Instagram Ads'), ('instagram_dms', 'Instagram DMs'), ('manual', 'Manual Entry')], default='website', max_length=20),
        ),
    ]
