# Generated by Django 6.0.5 on 2026-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Form'), ('google_forms', 'Google Forms'), ('instagram_ads', 'Instagram Ads'), ('instagram_dms', 'Instagram DMs'), ('manual', 'Manual Entry')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=50),
        ),
    ]
