# Generated by Django 6.0.5 on 2026-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_source_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(choices=[('website', 'Website Development'), ('app', 'App Development'), ('crm', 'CRM Software'), ('seo', 'SEO'), ('marketing', 'Digital Marketing'), ('uiux', 'UI/UX Design'), ('other', 'Other')], default='website', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Form'), ('google_forms', 'Google Forms'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('instagram_dms', 'Instagram DMs'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual Entry')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50),
        ),
    ]
