# Generated by Django 6.0.5 on 2026-05-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_company_lead_email_lead_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Form'), ('landing_page', 'Landing Page'), ('google_forms', 'Google Forms'), ('facebook_ads', 'Facebook Lead Ads'), ('instagram_ads', 'Instagram Ads'), ('instagram_dm', 'Instagram DM'), ('whatsapp', 'WhatsApp Inquiry'), ('manual', 'Manual Entry')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('converted', 'Converted'), ('not_interested', 'Not Interested'), ('closed', 'Closed')], default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(max_length=100)),
                ('task_type', models.CharField(default='Call Lead', max_length=100)),
                ('due_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
        ),
    ]
