# Generated by Django 6.0.5 on 2026-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_lead_company_remove_lead_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Form'), ('landing_page', 'Landing Page'), ('google_forms', 'Google Forms'), ('facebook_ads', 'Facebook Lead Ads'), ('instagram_ads', 'Instagram Ads'), ('instagram_dms', 'Instagram DM'), ('whatsapp', 'WhatsApp Inquiry'), ('manual', 'Manual Entry')], default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('converted', 'Converted'), ('not_interested', 'Not Interested'), ('closed', 'Closed'), ('qualified', 'Qualified'), ('meeting', 'Meeting Scheduled'), ('proposal', 'Proposal Sent'), ('lost', 'Lost')], default='new', max_length=30),
        ),
    ]
