# Generated by Django 6.0.5 on 2026-05-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_lead_source_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
