# Generated by Django 6.0.5 on 2026-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_ai_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='ai_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
